set(HEADER_FILES
	"Include/RHI/Commands.hpp"
	"Include/RHI/Device.hpp"
	"Include/RHI/Format.hpp"
	"Include/RHI/Instance.hpp"
	"Include/RHI/Memory.hpp"
	"Include/RHI/Resource.hpp"
	"Include/RHI/FrameGraph.hpp"
	"Include/RHI/Common.hpp"
	"Include/RHI/PipelineState.hpp"
	"Include/RHI/RHI.hpp"
	"Include/RHI/Swapchain.hpp"
	"Include/RHI/Core/Span.hpp"
	"Include/RHI/Core/Expected.hpp"
)

set(SOURCE_FILES
	"Source/Backend/Vulkan/Commands.cpp"
	"Source/Backend/Vulkan/Commands.hpp"
	"Source/Backend/Vulkan/Device.hpp"
	"Source/Backend/Vulkan/Instance.cpp"
	"Source/Backend/Vulkan/Resource.cpp"
	"Source/Backend/Vulkan/PipelineState.cpp"
	"Source/Backend/Vulkan/Device.cpp"
	"Source/Backend/Vulkan/Instance.hpp"
	"Source/Backend/Vulkan/Resource.hpp"
	"Source/Backend/Vulkan/PipelineState.hpp"
	"Source/Backend/Vulkan/Swapchain.hpp"
	"Source/Backend/Vulkan/Swapchain.cpp"
	"Source/RHI/Instance.cpp"
)

