name: Clang-Format Lint

on:
  pull_request:
    branches:
      - main

jobs:
  clang-format-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run clang-format linting
        run: |
          docker run --rm -v $(pwd):/src gnuradio/clang-format-lint
        working-directory: ${{ github.workspace }}
